module PromotionErrorCodes
  PROMOTION_NOT_FOUND = 'PROMOTION_NOT_FOUND'
  PROMOTION_INACTIVE = 'PROMOTION_INACTIVE'
  PROMOTION_USAGE_LIMIT_REACHED = 'PROMOTION_USAGE_LIMIT_REACHED'
  PROMOTION_ALREADY_APPLIED = 'PROMOTION_ALREADY_APPLIED'
  PROMOTION_NOT_STACKABLE = 'PROMOTION_NOT_STACKABLE'
  PROMOTION_VALIDATION_ERROR = 'PROMOTION_VALIDATION_ERROR'
  PROMOTION_UNEXPECTED_ERROR = 'PROMOTION_UNEXPECTED_ERROR'

  AUTO_APPLY_BUNDLE_FAILED = 'AUTO_APPLY_BUNDLE_FAILED'
  BUNDLE_EVALUATION_ERROR = 'BUNDLE_EVALUATION_ERROR'
  BUNDLE_PROMOTION_ADD_FAILED = 'BUNDLE_PROMOTION_ADD_FAILED'
end
